export const scoreOptions = [0, 2, 4, 5, 6, 6.5, 7, 7.5, 8]

export const roastOptions = [
	{ level: 'ライトロースト', color: '#F5F5DC' }, // アグトロン値: 91≦
	{ level: 'シナモンロースト', color: '#D2B48C' }, // アグトロン値: 81≦ and ≦ 90
	{ level: 'ミディアムロースト', color: '#A0522D' }, // アグトロン値: 71≦ and ≦ 80
	{ level: 'ハイロースト', color: '#8B4513' }, // アグトロン値: 61≦ and ≦ 70
	{ level: 'シティロースト', color: '#8B4513' }, // アグトロン値: 51≦ and ≦ 60
	{ level: 'フルシティロースト', color: '#603913' }, // アグトロン値: 41≦ and ≦ 50
	{ level: 'フレンチロースト', color: '#2F4F4F' }, // アグトロン値: 31≦ and ≦ 40
	{ level: 'イタリアンロースト', color: '#000000' }, // アグトロン値: ≦30
]

export const cleanCupOptions = [
	{ value: 'Clean', label: 'Clean', color: 'green' },
	{ value: 'Clear', label: 'Clear', color: 'green' },
	{ value: 'Super Clean', label: 'Super Clean', color: 'green' },
	{ value: 'Transparent', label: 'Transparent', color: 'green' },
	{ value: 'Refine', label: 'Refine', color: 'green' },
	{ value: 'Definition', label: 'Definition', color: 'green' },
	// ネガティブな要素
	{ value: 'Unclean', label: 'Unclean', color: 'red' },
	{ value: 'Rough', label: 'Rough', color: 'red' },
	{ value: 'Dusty', label: 'Dusty', color: 'red' },
	{ value: 'Dirty', label: 'Dirty', color: 'red' },
	{ value: 'Faded', label: 'Faded', color: 'red' },
	{ value: 'Woody', label: 'Woody', color: 'red' },
	{ value: 'Verde', label: 'Verde', color: 'red' },
	{ value: 'Grassy', label: 'Grassy', color: 'red' },
	{ value: 'Strawy', label: 'Strawy', color: 'red' },
	{ value: 'Astringent', label: 'Astringent', color: 'red' },
	{ value: 'Ashy', label: 'Ashy', color: 'red' },
	{ value: 'Moldy', label: 'Moldy', color: 'red' },
	{ value: 'Phenol', label: 'Phenol', color: 'red' },
	{ value: 'Earthy', label: 'Earthy', color: 'red' },
	{ value: 'Baggy', label: 'Baggy', color: 'red' },
	{ value: 'Fermented', label: 'Fermented', color: 'red' },
]

export const sweetnessOptions = [
	{ value: 'Sugarcane', label: 'Sugarcane', color: 'green' },
	{ value: 'Caramel', label: 'Caramel', color: 'green' },
	{ value: 'Vanilla', label: 'Vanilla', color: 'green' },
	{ value: 'Toffee', label: 'Toffee', color: 'green' },
	{ value: 'Chocolate', label: 'Chocolate', color: 'green' },
	{ value: 'Molasses', label: 'Molasses', color: 'green' },
	{ value: 'Maple Syrup', label: 'Maple Syrup', color: 'green' },
	{ value: 'Honey', label: 'Honey', color: 'green' },
	{ value: 'Sugar Sweet', label: 'Sugar Sweet', color: 'green' },
	{ value: 'Marzipan', label: 'Marzipan', color: 'green' },
	{ value: 'Gingerbread', label: 'Gingerbread', color: 'green' },
	{ value: 'Nougat', label: 'Nougat', color: 'green' },
	{ value: 'Butterscotch', label: 'Butterscotch', color: 'green' },
	{ value: 'Fudge', label: 'Fudge', color: 'green' },
	{ value: 'Licorice', label: 'Licorice', color: 'green' },
	{ value: 'Honeysuckle', label: 'Honeysuckle', color: 'green' },
	// ネガティブな要素
	{ value: 'Bitter', label: 'Bitter', color: 'red' },
	{ value: 'Burnt', label: 'Burnt', color: 'red' },
	{ value: 'Metallic', label: 'Metallic', color: 'red' },
	{ value: 'Smokey', label: 'Smokey', color: 'red' },
	{ value: 'Green', label: 'Green', color: 'red' },
	{ value: 'Un Ripen', label: 'Un Ripen', color: 'red' },
	{ value: 'Salty', label: 'Salty', color: 'red' },
]

export const acidityOptions = [
	{ value: 'Structure', label: 'Structure' },
	{ value: 'Crisp', label: 'Crisp' },
	{ value: 'Fizzy', label: 'Fizzy' },
	{ value: 'Sparkling', label: 'Sparkling' },
	{ value: 'Spine', label: 'Spine' },
	{ value: 'Bright', label: 'Bright' },
	{ value: 'Refine', label: 'Refine' },
	{ value: 'Juicy', label: 'Juicy' },
	{ value: 'Lively', label: 'Lively' },
	{ value: 'Effervescent', label: 'Effervescent' },
	{ value: 'Vibrant', label: 'Vibrant' },
	{ value: 'Refreshing', label: 'Refreshing' },
	// 有機酸等の表現
	{ value: 'Citric', label: 'Citric' },
	{ value: 'Malic', label: 'Malic' },
	{ value: 'Tartaric', label: 'Tartaric' },
	{ value: 'Lactic', label: 'Lactic' },
	{ value: 'Phosphoric', label: 'Phosphoric' },
	// ネガティブな要素
	{ value: 'Sharp', label: 'Sharp' },
	{ value: 'Dry', label: 'Dry' },
	{ value: 'Aggressive', label: 'Aggressive' },
	{ value: 'Pungent', label: 'Pungent' },
	{ value: 'Sour', label: 'Sour' },
	{ value: 'Fermented', label: 'Fermented' },
	{ value: 'Vinegar', label: 'Vinegar' },
	{ value: 'Tart', label: 'Tart' },
	{ value: 'Dull', label: 'Dull' },
	{ value: 'Harsh', label: 'Harsh' },
	{ value: 'Green', label: 'Green' },
	{ value: 'Immature', label: 'Immature' },
]

export const mouthfeelOptions = [
	{ value: 'Structure', label: 'Structure' },
	{ value: 'Rich', label: 'Rich' },
	{ value: 'Thick', label: 'Thick' },
	{ value: 'Round', label: 'Round' },
	{ value: 'Smooth', label: 'Smooth' },
	{ value: 'Silky', label: 'Silky' },
	{ value: 'Syrupy', label: 'Syrupy' },
	{ value: 'Velvety', label: 'Velvety' },
	{ value: 'Creamy', label: 'Creamy' },
	{ value: 'Heavy Body', label: 'Heavy Body' },
	{ value: 'Medium Body', label: 'Medium Body' },
	{ value: 'Light Body', label: 'Light Body' },
	{ value: 'Big Mouthfeel', label: 'Big Mouthfeel' },
	{ value: 'Buttery', label: 'Buttery' },
	{ value: 'Viscous', label: 'Viscous' },
	{ value: 'Juicy', label: 'Juicy' },
	{ value: 'Consistent Body', label: 'Consistent Body' },
	{ value: 'Dense', label: 'Dense' },
	{ value: 'Sexy', label: 'Sexy' },
	{ value: 'Tannic', label: 'Tannic' },
	{ value: 'Rough', label: 'Rough' },
	{ value: 'Pungent', label: 'Pungent' },
	{ value: 'Peppery', label: 'Peppery' },
	{ value: 'Dry', label: 'Dry' },
	{ value: 'Not Smooth', label: 'Not Smooth' },
	{ value: 'Matte', label: 'Matte' },
	{ value: 'Astringent', label: 'Astringent' },
	{ value: 'Watery', label: 'Watery' },
	{ value: 'Powdery', label: 'Powdery' },
]

export const flavorOptions = [
	{ value: 'Peach', label: 'Peach' },
	{ value: 'Bergamot', label: 'Bergamot' },
	{ value: 'Vanilla', label: 'Vanilla' },
	{ value: 'Mango', label: 'Mango' },
	{ value: 'Chamomile', label: 'Chamomile' },
	{ value: 'Sprite', label: 'Sprite' },
	{ value: 'Grapefruit', label: 'Grapefruit' },
	{ value: 'Jasmine', label: 'Jasmine' },
	{ value: 'Aloe', label: 'Aloe' },
	{ value: 'Pineapple', label: 'Pineapple' },
	{ value: 'Cranberry', label: 'Cranberry' },
	{ value: 'Peach Blossom', label: 'Peach Blossom' },
	{ value: 'Kiwi', label: 'Kiwi' },
	{ value: 'Brown Sugar', label: 'Brown Sugar' },
	{ value: 'Watermelon Candy', label: 'Watermelon Candy' },
	{ value: 'Sugar Cane', label: 'Sugar Cane' },
	{ value: 'Gooseberries', label: 'Gooseberries' },
	{ value: 'Orange', label: 'Orange' },
	{ value: 'Green Tea', label: 'Green Tea' },
	{ value: 'Tropical Fruit', label: 'Tropical Fruit' },
	{ value: 'Honey', label: 'Honey' },
	{ value: 'Banana', label: 'Banana' },
	{ value: 'Toffee', label: 'Toffee' },
	{ value: 'Molasses', label: 'Molasses' },
	{ value: 'Strawberry', label: 'Strawberry' },
	{ value: 'Tangerine', label: 'Tangerine' },
	{ value: 'Marshmallow', label: 'Marshmallow' },
	{ value: 'Green Grape', label: 'Green Grape' },
	{ value: 'Lemon Grass', label: 'Lemon Grass' },
	{ value: 'Cherry Blossom', label: 'Cherry Blossom' },
	{ value: 'Rose', label: 'Rose' },
	{ value: 'Perfume', label: 'Perfume' },
	{ value: 'Fig', label: 'Fig' },
	{ value: 'Raisin', label: 'Raisin' },
	{ value: 'Red Berries', label: 'Red Berries' },
	{ value: 'Dried Cherries', label: 'Dried Cherries' },
	{ value: 'Black Berry', label: 'Black Berry' },
	{ value: 'Black Currant', label: 'Black Currant' },
	{ value: 'Guava', label: 'Guava' },
	{ value: 'Lime Zest', label: 'Lime Zest' },
	{ value: 'Apricot', label: 'Apricot' },
	{ value: 'Floral', label: 'Floral' },
	{ value: 'Red Grape', label: 'Red Grape' },
	{ value: 'Red Apple Black Tea', label: 'Red Apple Black Tea' },
	{ value: 'Dark Chocolate', label: 'Dark Chocolate' },
	{ value: 'Blueberry', label: 'Blueberry' },
	{ value: 'Jammy', label: 'Jammy' },
	{ value: 'Orange Peel', label: 'Orange Peel' },
	{ value: 'Lychee', label: 'Lychee' },
	{ value: 'Cognac', label: 'Cognac' },
	{ value: 'Wine', label: 'Wine' },
	{ value: 'Red Currant', label: 'Red Currant' },
	{ value: 'Oolong Tea', label: 'Oolong Tea' },
	{ value: 'Marzipan', label: 'Marzipan' },
	{ value: 'Cocoa', label: 'Cocoa' },
	{ value: 'Pomelo', label: 'Pomelo' },
	{ value: 'Cardamom', label: 'Cardamom' },
	{ value: 'Coriander Seeds', label: 'Coriander Seeds' },
	{ value: 'Earl Grey', label: 'Earl Grey' },
	{ value: 'Champagne', label: 'Champagne' },
	{ value: 'Stone Fruits', label: 'Stone Fruits' },
	{ value: 'Melon', label: 'Melon' },
	{ value: 'Coffee Blossoms', label: 'Coffee Blossoms' },
	{ value: 'Osmanthus Flower', label: 'Osmanthus Flower' },
	{ value: 'Violet Flower', label: 'Violet Flower' },
	{ value: 'Tamarind', label: 'Tamarind' },
	{ value: 'Alcohol', label: 'Alcohol' },
	{ value: 'Raspberry', label: 'Raspberry' },
	{ value: 'Passion Fruit', label: 'Passion Fruit' },
	{ value: 'Cedar', label: 'Cedar' },
	{ value: 'Roselle', label: 'Roselle' },
	{ value: 'Turkish Delight', label: 'Turkish Delight' },
	{ value: 'Rum', label: 'Rum' },
	{ value: 'White Wine', label: 'White Wine' },
	{ value: 'Mesquite', label: 'Mesquite' },
	{ value: 'Blue Berry', label: 'Blue Berry' },
	{ value: 'Papaya', label: 'Papaya' },
	{ value: 'Yogurt', label: 'Yogurt' },
	{ value: 'Plum', label: 'Plum' },
	{ value: 'Pineapple', label: 'Pineapple' },
	{ value: 'White Berries', label: 'White Berries' },
	{ value: 'Almond', label: 'Almond' },
	{ value: 'Dry Apricot', label: 'Dry Apricot' },
	{ value: 'Malt', label: 'Malt' },
	{ value: 'Licorice', label: 'Licorice' },
	{ value: 'Honeysuckle', label: 'Honeysuckle' },
	{ value: 'Lavender', label: 'Lavender' },
	{ value: 'Port Wine', label: 'Port Wine' },
	{ value: 'Prune', label: 'Prune' },
	{ value: 'Rhubarb', label: 'Rhubarb' },
	{ value: 'Apple Cider', label: 'Apple Cider' },
	{ value: 'Jackfruit', label: 'Jackfruit' },
	{ value: 'Hibiscus', label: 'Hibiscus' },
	{ value: 'Panela', label: 'Panela' },
	{ value: 'Hazelnut', label: 'Hazelnut' },
	{ value: 'Brulee', label: 'Brulee' },
	{ value: 'Pear', label: 'Pear' },
	{ value: 'Bergamot', label: 'Bergamot' },
	{ value: 'Rose Hip', label: 'Rose Hip' },
	{ value: 'Orange Blossom', label: 'Orange Blossom' },
	{ value: 'Nectarine', label: 'Nectarine' },
	{ value: 'Anis', label: 'Anis' },
	{ value: 'Lime', label: 'Lime' },
	{ value: 'Ginger', label: 'Ginger' },
	{ value: 'Marmalade', label: 'Marmalade' },
	{ value: 'Dulce de Leche', label: 'Dulce de Leche' },
	{ value: 'Sweet Potato', label: 'Sweet Potato' },
	{ value: 'Chestnut', label: 'Chestnut' },
	{ value: 'Clove', label: 'Clove' },
	{ value: 'Toasted Marshmallow', label: 'Toasted Marshmallow' },
	{ value: 'Caraway Seed', label: 'Caraway Seed' },
	{ value: 'Eucalyptus', label: 'Eucalyptus' },
	{ value: 'Pomegranate', label: 'Pomegranate' },
	{ value: 'Mint', label: 'Mint' },
	{ value: 'Coca Cola', label: 'Coca Cola' },
	{ value: 'Grape Bubblegum', label: 'Grape Bubblegum' },
	{ value: 'Wine Vinegar', label: 'Wine Vinegar' },
	{ value: 'Balsamic Vinegar', label: 'Balsamic Vinegar' },
	{ value: 'Tobacco', label: 'Tobacco' },
	{ value: 'Ethnic Earthy', label: 'Ethnic Earthy' },
	{ value: 'Guarana', label: 'Guarana' },
	{ value: 'Wine Vinegar', label: 'Wine Vinegar' },
	{ value: 'Mandarin Orange', label: 'Mandarin Orange' },
	{ value: 'Fuji Apple', label: 'Fuji Apple' },
]

export const aftertasteOptions = [
	{ value: 'Long Lingering Aftertaste', label: 'Long Lingering Aftertaste' },
	{ value: 'Sweet After Taste', label: 'Sweet After Taste' },
	{ value: 'Long Lasting', label: 'Long Lasting' },
	{ value: 'Persistent', label: 'Persistent' },
	{ value: 'Clean Finish', label: 'Clean Finish' },
	{ value: 'Everlasting', label: 'Everlasting' },
	// ネガティブな要素
	{ value: 'Short', label: 'Short' },
	{ value: 'Unpleasant', label: 'Unpleasant' },
	{ value: 'Fast Going', label: 'Fast Going' },
	{ value: 'Quick Disappearing', label: 'Quick Disappearing' },
	{ value: 'Rough', label: 'Rough' },
	{ value: 'Bitter', label: 'Bitter' },
	{ value: 'Tannin', label: 'Tannin' },
	{ value: 'Astringent', label: 'Astringent' },
	{ value: 'Metallic', label: 'Metallic' },
	{ value: 'Scorched', label: 'Scorched' },
	{ value: 'Pungent', label: 'Pungent' },
]

export const balanceOptions = [
	{ value: 'Complex', label: 'Complex' },
	{ value: 'Delicate', label: 'Delicate' },
	{ value: 'Consistent', label: 'Consistent' },
	{ value: 'Elegant', label: 'Elegant' },
	{ value: 'Tune', label: 'Tune' },
	{ value: 'Improved as cooled', label: 'Improved as cooled' },
	{ value: 'Well Layered', label: 'Well Layered' },
	{ value: 'Subtle', label: 'Subtle' },
	{ value: 'Harmony', label: 'Harmony' },
	{ value: 'Composed', label: 'Composed' },
	// ネガティブな要素
	{ value: 'Unbalanced', label: 'Unbalanced' },
	{ value: 'Not Harmonious', label: 'Not Harmonious' },
	{ value: 'Inconsistent', label: 'Inconsistent' },
	{ value: 'Decline', label: 'Decline' },
	{ value: 'Flat', label: 'Flat' },
]

export const overallOptions = [
	{ value: 'Exotic', label: 'Exotic' },
	{ value: 'Structured', label: 'Structured' },
	{ value: 'Elegant', label: 'Elegant' },
	{ value: 'Stable', label: 'Stable' },
	{ value: 'Soft', label: 'Soft' },
	{ value: 'Multi-Dimensional', label: 'Multi-Dimensional' },
	{ value: 'Unique', label: 'Unique' },
	{ value: 'Great', label: 'Great' },
	// ネガティブな要素
	{ value: 'Unpleasant', label: 'Unpleasant' },
	{ value: 'Boring', label: 'Boring' },
	{ value: 'Simple', label: 'Simple' },
	{ value: 'Do Not Like', label: 'Do Not Like' },
]
