export const scoreOptions = [0, 2, 4, 5, 6, 6.5, 7, 7.5, 8]

export const roastOptions = [
	{ level: 'ライトロースト', color: '#F5F5DC' }, // アグトロン値: 91≦
	{ level: 'シナモンロースト', color: '#D2B48C' }, // アグトロン値: 81≦ and ≦ 90
	{ level: 'ミディアムロースト', color: '#A0522D' }, // アグトロン値: 71≦ and ≦ 80
	{ level: 'ハイロースト', color: '#8B4513' }, // アグトロン値: 61≦ and ≦ 70
	{ level: 'シティロースト', color: '#8B4513' }, // アグトロン値: 51≦ and ≦ 60
	{ level: 'フルシティロースト', color: '#603913' }, // アグトロン値: 41≦ and ≦ 50
	{ level: 'フレンチロースト', color: '#2F4F4F' }, // アグトロン値: 31≦ and ≦ 40
	{ level: 'イタリアンロースト', color: '#000000' }, // アグトロン値: ≦30
]

export const cleanCupOptions = [
	{ value: 'Clean', label: 'Clean', color: 'green' },
	{ value: 'Clear', label: 'Clear', color: 'green' },
	{ value: 'Super Clean', label: 'Super Clean', color: 'green' },
	{ value: 'Transparent', label: 'Transparent', color: 'green' },
	{ value: 'Refine', label: 'Refine', color: 'green' },
	{ value: 'Definition', label: 'Definition', color: 'green' },
	// ネガティブな要素
	{ value: 'Unclean', label: 'Unclean', color: 'red' },
	{ value: 'Rough', label: 'Rough', color: 'red' },
	{ value: 'Dusty', label: 'Dusty', color: 'red' },
	{ value: 'Dirty', label: 'Dirty', color: 'red' },
	{ value: 'Faded', label: 'Faded', color: 'red' },
	{ value: 'Woody', label: 'Woody', color: 'red' },
	{ value: 'Verde', label: 'Verde', color: 'red' },
	{ value: 'Grassy', label: 'Grassy', color: 'red' },
	{ value: 'Strawy', label: 'Strawy', color: 'red' },
	{ value: 'Astringent', label: 'Astringent', color: 'red' },
	{ value: 'Ashy', label: 'Ashy', color: 'red' },
	{ value: 'Moldy', label: 'Moldy', color: 'red' },
	{ value: 'Phenol', label: 'Phenol', color: 'red' },
	{ value: 'Earthy', label: 'Earthy', color: 'red' },
	{ value: 'Baggy', label: 'Baggy', color: 'red' },
	{ value: 'Fermented', label: 'Fermented', color: 'red' },
]

export const sweetnessOptions = [
	{ value: 'Sugarcane', label: 'Sugarcane', color: 'green' },
	{ value: 'Caramel', label: 'Caramel', color: 'green' },
	{ value: 'Vanilla', label: 'Vanilla', color: 'green' },
	{ value: 'Toffee', label: 'Toffee', color: 'green' },
	{ value: 'Chocolate', label: 'Chocolate', color: 'green' },
	{ value: 'Molasses', label: 'Molasses', color: 'green' },
	{ value: 'Maple Syrup', label: 'Maple Syrup', color: 'green' },
	{ value: 'Honey', label: 'Honey', color: 'green' },
	{ value: 'Sugar Sweet', label: 'Sugar Sweet', color: 'green' },
	{ value: 'Marzipan', label: 'Marzipan', color: 'green' },
	{ value: 'Gingerbread', label: 'Gingerbread', color: 'green' },
	{ value: 'Nougat', label: 'Nougat', color: 'green' },
	{ value: 'Butterscotch', label: 'Butterscotch', color: 'green' },
	{ value: 'Fudge', label: 'Fudge', color: 'green' },
	{ value: 'Licorice', label: 'Licorice', color: 'green' },
	{ value: 'Honeysuckle', label: 'Honeysuckle', color: 'green' },
	// ネガティブな要素
	{ value: 'Bitter', label: 'Bitter', color: 'red' },
	{ value: 'Burnt', label: 'Burnt', color: 'red' },
	{ value: 'Metallic', label: 'Metallic', color: 'red' },
	{ value: 'Smokey', label: 'Smokey', color: 'red' },
	{ value: 'Green', label: 'Green', color: 'red' },
	{ value: 'Un Ripen', label: 'Un Ripen', color: 'red' },
	{ value: 'Salty', label: 'Salty', color: 'red' },
]

export const acidityOptions = [
	{ value: 'Structure', label: 'Structure', color: 'green' },
	{ value: 'Crisp', label: 'Crisp', color: 'green' },
	{ value: 'Fizzy', label: 'Fizzy', color: 'green' },
	{ value: 'Sparkling', label: 'Sparkling', color: 'green' },
	{ value: 'Spine', label: 'Spine', color: 'green' },
	{ value: 'Bright', label: 'Bright', color: 'green' },
	{ value: 'Refine', label: 'Refine', color: 'green' },
	{ value: 'Juicy', label: 'Juicy', color: 'green' },
	{ value: 'Lively', label: 'Lively', color: 'green' },
	{ value: 'Effervescent', label: 'Effervescent', color: 'green' },
	{ value: 'Vibrant', label: 'Vibrant', color: 'green' },
	{ value: 'Refreshing', label: 'Refreshing', color: 'green' },
	{ value: 'Citric', label: 'Citric', color: 'green' },
	{ value: 'Malic', label: 'Malic', color: 'green' },
	{ value: 'Tartaric', label: 'Tartaric', color: 'green' },
	{ value: 'Lactic', label: 'Lactic', color: 'green' },
	{ value: 'Phosphoric', label: 'Phosphoric', color: 'green' },
	{ value: 'Sharp', label: 'Sharp', color: 'red' },
	{ value: 'Dry', label: 'Dry', color: 'red' },
	{ value: 'Aggressive', label: 'Aggressive', color: 'red' },
	{ value: 'Pungent', label: 'Pungent', color: 'red' },
	{ value: 'Sour', label: 'Sour', color: 'red' },
	{ value: 'Fermented', label: 'Fermented', color: 'red' },
	{ value: 'Vinegar', label: 'Vinegar', color: 'red' },
	{ value: 'Tart', label: 'Tart', color: 'red' },
	{ value: 'Dull', label: 'Dull', color: 'red' },
	{ value: 'Harsh', label: 'Harsh', color: 'red' },
	{ value: 'Green', label: 'Green', color: 'red' },
	{ value: 'Immature', label: 'Immature', color: 'red' },
]

export const mouthfeelOptions = [
	{ value: 'Structure', label: 'Structure', color: 'green' },
	{ value: 'Rich', label: 'Rich', color: 'green' },
	{ value: 'Thick', label: 'Thick', color: 'green' },
	{ value: 'Round', label: 'Round', color: 'green' },
	{ value: 'Smooth', label: 'Smooth', color: 'green' },
	{ value: 'Silky', label: 'Silky', color: 'green' },
	{ value: 'Syrupy', label: 'Syrupy', color: 'green' },
	{ value: 'Velvety', label: 'Velvety', color: 'green' },
	{ value: 'Creamy', label: 'Creamy', color: 'green' },
	{ value: 'Heavy Body', label: 'Heavy Body', color: 'green' },
	{ value: 'Medium Body', label: 'Medium Body', color: 'green' },
	{ value: 'Light Body', label: 'Light Body', color: 'green' },
	{ value: 'Big Mouthfeel', label: 'Big Mouthfeel', color: 'green' },
	{ value: 'Buttery', label: 'Buttery', color: 'green' },
	{ value: 'Viscous', label: 'Viscous', color: 'green' },
	{ value: 'Juicy', label: 'Juicy', color: 'green' },
	{ value: 'Consistent Body', label: 'Consistent Body', color: 'green' },
	{ value: 'Dense', label: 'Dense', color: 'green' },
	{ value: 'Sexy', label: 'Sexy', color: 'green' },
	{ value: 'Tannic', label: 'Tannic', color: 'red' },
	{ value: 'Rough', label: 'Rough', color: 'red' },
	{ value: 'Pungent', label: 'Pungent', color: 'red' },
	{ value: 'Peppery', label: 'Peppery', color: 'red' },
	{ value: 'Dry', label: 'Dry', color: 'red' },
	{ value: 'Not Smooth', label: 'Not Smooth', color: 'red' },
	{ value: 'Matte', label: 'Matte', color: 'red' },
	{ value: 'Astringent', label: 'Astringent', color: 'red' },
	{ value: 'Watery', label: 'Watery', color: 'red' },
	{ value: 'Powdery', label: 'Powdery', color: 'red' },
]

export const flavorOptions = [
	{ value: 'Peach', label: 'Peach', color: 'green' },
	{ value: 'Bergamot', label: 'Bergamot', color: 'green' },
	{ value: 'Vanilla', label: 'Vanilla', color: 'green' },
	{ value: 'Mango', label: 'Mango', color: 'green' },
	{ value: 'Chamomile', label: 'Chamomile', color: 'green' },
	{ value: 'Sprite', label: 'Sprite', color: 'green' },
	{ value: 'Grapefruit', label: 'Grapefruit', color: 'green' },
	{ value: 'Jasmine', label: 'Jasmine', color: 'green' },
	{ value: 'Aloe', label: 'Aloe', color: 'green' },
	{ value: 'Pineapple', label: 'Pineapple', color: 'green' },
	{ value: 'Cranberry', label: 'Cranberry', color: 'green' },
	{ value: 'Peach Blossom', label: 'Peach Blossom', color: 'green' },
	{ value: 'Kiwi', label: 'Kiwi', color: 'green' },
	{ value: 'Brown Sugar', label: 'Brown Sugar', color: 'green' },
	{ value: 'Watermelon Candy', label: 'Watermelon Candy', color: 'green' },
	{ value: 'Sugar Cane', label: 'Sugar Cane', color: 'green' },
	{ value: 'Gooseberries', label: 'Gooseberries', color: 'green' },
	{ value: 'Orange', label: 'Orange', color: 'green' },
	{ value: 'Green Tea', label: 'Green Tea', color: 'green' },
	{ value: 'Tropical Fruit', label: 'Tropical Fruit', color: 'green' },
	{ value: 'Honey', label: 'Honey', color: 'green' },
	{ value: 'Banana', label: 'Banana', color: 'green' },
	{ value: 'Toffee', label: 'Toffee', color: 'green' },
	{ value: 'Molasses', label: 'Molasses', color: 'green' },
	{ value: 'Strawberry', label: 'Strawberry', color: 'green' },
	{ value: 'Tangerine', label: 'Tangerine', color: 'green' },
	{ value: 'Marshmallow', label: 'Marshmallow', color: 'green' },
	{ value: 'Green Grape', label: 'Green Grape', color: 'green' },
	{ value: 'Lemon Grass', label: 'Lemon Grass', color: 'green' },
	{ value: 'Cherry Blossom', label: 'Cherry Blossom', color: 'green' },
	{ value: 'Rose', label: 'Rose', color: 'green' },
	{ value: 'Perfume', label: 'Perfume', color: 'green' },
	{ value: 'Fig', label: 'Fig', color: 'green' },
	{ value: 'Raisin', label: 'Raisin', color: 'green' },
	{ value: 'Red Berries', label: 'Red Berries', color: 'green' },
	{ value: 'Dried Cherries', label: 'Dried Cherries', color: 'green' },
	{ value: 'Black Berry', label: 'Black Berry', color: 'green' },
	{ value: 'Black Currant', label: 'Black Currant', color: 'green' },
	{ value: 'Guava', label: 'Guava', color: 'green' },
	{ value: 'Lime Zest', label: 'Lime Zest', color: 'green' },
	{ value: 'Apricot', label: 'Apricot', color: 'green' },
	{ value: 'Floral', label: 'Floral', color: 'green' },
	{ value: 'Red Grape', label: 'Red Grape', color: 'green' },
	{
		value: 'Red Apple Black Tea',
		label: 'Red Apple Black Tea',
		color: 'green',
	},
	{ value: 'Dark Chocolate', label: 'Dark Chocolate', color: 'green' },
	{ value: 'Blueberry', label: 'Blueberry', color: 'green' },
	{ value: 'Jammy', label: 'Jammy', color: 'green' },
	{ value: 'Orange Peel', label: 'Orange Peel', color: 'green' },
	{ value: 'Lychee', label: 'Lychee', color: 'green' },
	{ value: 'Cognac', label: 'Cognac', color: 'green' },
	{ value: 'Wine', label: 'Wine', color: 'green' },
	{ value: 'Red Currant', label: 'Red Currant', color: 'green' },
	{ value: 'Oolong Tea', label: 'Oolong Tea', color: 'green' },
	{ value: 'Marzipan', label: 'Marzipan', color: 'green' },
	{ value: 'Cocoa', label: 'Cocoa', color: 'green' },
	{ value: 'Pomelo', label: 'Pomelo', color: 'green' },
	{ value: 'Cardamom', label: 'Cardamom', color: 'green' },
	{ value: 'Coriander Seeds', label: 'Coriander Seeds', color: 'green' },
	{ value: 'Earl Grey', label: 'Earl Grey', color: 'green' },
	{ value: 'Champagne', label: 'Champagne', color: 'green' },
	{ value: 'Stone Fruits', label: 'Stone Fruits', color: 'green' },
	{ value: 'Melon', label: 'Melon', color: 'green' },
	{ value: 'Coffee Blossoms', label: 'Coffee Blossoms', color: 'green' },
	{ value: 'Osmanthus Flower', label: 'Osmanthus Flower', color: 'green' },
	{ value: 'Violet Flower', label: 'Violet Flower', color: 'green' },
	{ value: 'Tamarind', label: 'Tamarind', color: 'green' },
	{ value: 'Alcohol', label: 'Alcohol', color: 'green' },
	{ value: 'Raspberry', label: 'Raspberry', color: 'green' },
	{ value: 'Passion Fruit', label: 'Passion Fruit', color: 'green' },
	{ value: 'Cedar', label: 'Cedar', color: 'green' },
	{ value: 'Roselle', label: 'Roselle', color: 'green' },
	{ value: 'Turkish Delight', label: 'Turkish Delight', color: 'green' },
	{ value: 'Rum', label: 'Rum', color: 'green' },
	{ value: 'White Wine', label: 'White Wine', color: 'green' },
	{ value: 'Mesquite', label: 'Mesquite', color: 'green' },
	{ value: 'Blue Berry', label: 'Blue Berry', color: 'green' },
	{ value: 'Papaya', label: 'Papaya', color: 'green' },
	{ value: 'Yogurt', label: 'Yogurt', color: 'green' },
	{ value: 'Plum', label: 'Plum', color: 'green' },
	{ value: 'Pineapple', label: 'Pineapple', color: 'green' },
	{ value: 'White Berries', label: 'White Berries', color: 'green' },
	{ value: 'Almond', label: 'Almond', color: 'green' },
	{ value: 'Dry Apricot', label: 'Dry Apricot', color: 'green' },
	{ value: 'Malt', label: 'Malt', color: 'green' },
	{ value: 'Licorice', label: 'Licorice', color: 'green' },
	{ value: 'Honeysuckle', label: 'Honeysuckle', color: 'green' },
	{ value: 'Lavender', label: 'Lavender', color: 'green' },
	{ value: 'Port Wine', label: 'Port Wine', color: 'green' },
	{ value: 'Prune', label: 'Prune', color: 'green' },
	{ value: 'Rhubarb', label: 'Rhubarb', color: 'green' },
	{ value: 'Apple Cider', label: 'Apple Cider', color: 'green' },
	{ value: 'Jackfruit', label: 'Jackfruit', color: 'green' },
	{ value: 'Hibiscus', label: 'Hibiscus', color: 'green' },
	{ value: 'Panela', label: 'Panela', color: 'green' },
	{ value: 'Hazelnut', label: 'Hazelnut', color: 'green' },
	{ value: 'Brulee', label: 'Brulee', color: 'green' },
	{ value: 'Pear', label: 'Pear', color: 'green' },
	{ value: 'Bergamot', label: 'Bergamot', color: 'green' },
	{ value: 'Rose Hip', label: 'Rose Hip', color: 'green' },
	{ value: 'Orange Blossom', label: 'Orange Blossom', color: 'green' },
	{ value: 'Nectarine', label: 'Nectarine', color: 'green' },
	{ value: 'Anis', label: 'Anis', color: 'green' },
	{ value: 'Lime', label: 'Lime', color: 'green' },
	{ value: 'Ginger', label: 'Ginger', color: 'green' },
	{ value: 'Marmalade', label: 'Marmalade', color: 'green' },
	{ value: 'Dulce de Leche', label: 'Dulce de Leche', color: 'green' },
	{ value: 'Sweet Potato', label: 'Sweet Potato', color: 'green' },
	{ value: 'Chestnut', label: 'Chestnut', color: 'green' },
	{ value: 'Clove', label: 'Clove', color: 'green' },
	{
		value: 'Toasted Marshmallow',
		label: 'Toasted Marshmallow',
		color: 'green',
	},
	{ value: 'Caraway Seed', label: 'Caraway Seed', color: 'green' },
	{ value: 'Eucalyptus', label: 'Eucalyptus', color: 'green' },
	{ value: 'Pomegranate', label: 'Pomegranate', color: 'green' },
	{ value: 'Mint', label: 'Mint', color: 'green' },
	{ value: 'Coca Cola', label: 'Coca Cola', color: 'green' },
	{ value: 'Grape Bubblegum', label: 'Grape Bubblegum', color: 'green' },
	{ value: 'Wine Vinegar', label: 'Wine Vinegar', color: 'green' },
	{ value: 'Balsamic Vinegar', label: 'Balsamic Vinegar', color: 'green' },
	{ value: 'Tobacco', label: 'Tobacco', color: 'green' },
	{ value: 'Ethnic Earthy', label: 'Ethnic Earthy', color: 'green' },
	{ value: 'Guarana', label: 'Guarana', color: 'green' },
	{ value: 'Wine Vinegar', label: 'Wine Vinegar', color: 'green' },
	{ value: 'Mandarin Orange', label: 'Mandarin Orange', color: 'green' },
	{ value: 'Fuji Apple', label: 'Fuji Apple', color: 'green' },
	{ value: 'Flat', label: 'Flat', color: 'red' },
	{ value: 'Green', label: 'Green', color: 'red' },
	{ value: 'Unripen', label: 'Unripen', color: 'red' },
	{ value: 'Nutty', label: 'Nutty', color: 'red' },
	{ value: 'Vegetative', label: 'Vegetative', color: 'red' },
	{ value: 'Woody', label: 'Woody', color: 'red' },
	{ value: 'Strawy', label: 'Strawy', color: 'red' },
	{ value: 'Earthy', label: 'Earthy', color: 'red' },
	{ value: 'Potato', label: 'Potato', color: 'red' },
	{ value: 'Phenol', label: 'Phenol', color: 'red' },
	{ value: 'Peasy', label: 'Peasy', color: 'red' },
	{ value: 'Peanut', label: 'Peanut', color: 'red' },
	{ value: 'Cereal', label: 'Cereal', color: 'red' },
	{ value: 'Parchment', label: 'Parchment', color: 'red' },
	{ value: 'Baggy', label: 'Baggy', color: 'red' },
	{ value: 'Soy Bean', label: 'Soy Bean', color: 'red' },
	{ value: 'Oat', label: 'Oat', color: 'red' },
]

export const aftertasteOptions = [
	{
		value: 'Long Lingering Aftertaste',
		label: 'Long Lingering Aftertaste',
		color: 'green',
	},
	{ value: 'Sweet After Taste', label: 'Sweet After Taste', color: 'green' },
	{ value: 'Long Lasting', label: 'Long Lasting', color: 'green' },
	{ value: 'Persistent', label: 'Persistent', color: 'green' },
	{ value: 'Clean Finish', label: 'Clean Finish', color: 'green' },
	{ value: 'Everlasting', label: 'Everlasting', color: 'green' },
	{ value: 'Short', label: 'Short', color: 'red' },
	{ value: 'Unpleasant', label: 'Unpleasant', color: 'red' },
	{ value: 'Fast Going', label: 'Fast Going', color: 'red' },
	{ value: 'Quick Disappearing', label: 'Quick Disappearing', color: 'red' },
	{ value: 'Rough', label: 'Rough', color: 'red' },
	{ value: 'Bitter', label: 'Bitter', color: 'red' },
	{ value: 'Tannin', label: 'Tannin', color: 'red' },
	{ value: 'Astringent', label: 'Astringent', color: 'red' },
	{ value: 'Metallic', label: 'Metallic', color: 'red' },
	{ value: 'Scorched', label: 'Scorched', color: 'red' },
	{ value: 'Pungent', label: 'Pungent', color: 'red' },
]

export const balanceOptions = [
	{ value: 'Complex', label: 'Complex', color: 'green' },
	{ value: 'Delicate', label: 'Delicate', color: 'green' },
	{ value: 'Consistent', label: 'Consistent', color: 'green' },
	{ value: 'Elegant', label: 'Elegant', color: 'green' },
	{ value: 'Tune', label: 'Tune', color: 'green' },
	{
		value: 'Improved as cooled',
		label: 'Improved as cooled',
		color: 'green',
	},
	{ value: 'Well Layered', label: 'Well Layered', color: 'green' },
	{ value: 'Subtle', label: 'Subtle', color: 'green' },
	{ value: 'Harmony', label: 'Harmony', color: 'green' },
	{ value: 'Composed', label: 'Composed', color: 'green' },
	{ value: 'Unbalanced', label: 'Unbalanced', color: 'red' },
	{ value: 'Not Harmonious', label: 'Not Harmonious', color: 'red' },
	{ value: 'Inconsistent', label: 'Inconsistent', color: 'red' },
	{ value: 'Decline', label: 'Decline', color: 'red' },
	{ value: 'Flat', label: 'Flat', color: 'red' },
]

export const overallOptions = [
	{ value: 'Exotic', label: 'Exotic', color: 'green' },
	{ value: 'Structured', label: 'Structured', color: 'green' },
	{ value: 'Elegant', label: 'Elegant', color: 'green' },
	{ value: 'Stable', label: 'Stable', color: 'green' },
	{ value: 'Soft', label: 'Soft', color: 'green' },
	{ value: 'Multi-Dimensional', label: 'Multi-Dimensional', color: 'green' },
	{ value: 'Unique', label: 'Unique', color: 'green' },
	{ value: 'Great', label: 'Great', color: 'green' },
	{ value: 'Unpleasant', label: 'Unpleasant', color: 'red' },
	{ value: 'Boring', label: 'Boring', color: 'red' },
	{ value: 'Simple', label: 'Simple', color: 'red' },
	{ value: 'Do Not Like', label: 'Do Not Like', color: 'red' },
]
