name: Lint and Format Check

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn upgrade && yarn install

      - name: Run ESLint
        run: yarn eslint

      - name: Run Prettier Check
        run: yarn prettier --check .
